### ISSUE TITLE
missing repos

### ISSUE THREAD

**Issue by faveoled** [VictorX6996/release#1]
Hey, do you by any chance have those repos saved somewhere?
[https://github.com/Johnnyhandsome69/android_kernel_samsung_a30](https://github.com/Johnnyhandsome69/android_kernel_samsung_a30)
[https://github.com/Johnnyhandsome69/proprietary_vendor_a305](https://github.com/Johnnyhandsome69/proprietary_vendor_a305)

**Comment by VictorX6996** [comment]
I changed it to private
If you want, I can add you to access the sources

**Comment by faveoled** [comment]
@Johnnyhandsome69, yes, I would love to
