### ISSUE TITLE
missing repos :(

### ISSUE THREAD

**Issue by giutrec** [VictorX6996/release#2]
Hi, do you have a copy of this your repos?
https://github.com/Johnnyhandsome69/android_kernel_samsung_a30
https://github.com/Johnnyhandsome69/proprietary_vendor_a305

Because i think to port che some architecture to Samsung A40.

Thanks :)

**Comment by VictorX6996** [comment]
@giutrec Added to the sources

**Comment by giutrec** [comment]
@Johnnyhandsome69 thanks!!!
